### ISSUE TITLE
Export non-HOC version?

### ISSUE THREAD

**Issue by mnpenner** [NoamELB/shouldComponentUpdate-Children#2]
I know you said in the README that you love HOCs, but I don't see the benefit of adding another level to my component tree when it's not needed. It'd be trivial to add one more little export:

```js
export function shouldComponentUpdate(nextProps, nextState) {
    return !shallowEqualState(this.state, nextState) || !shallowEqualWithoutReactElements(this.props, nextProps);
}
```

Could you add it please? :heart: 

PS: This thing is working like magic. Much less rendering with no ill-effects so far.

**Comment by NoamELB** [comment]
Yes, great idea!
Will do 😁

Edit: Just note that you need to pass current state & prop
so it will be more like this:
```js
export function shallowEqual(thisProps, nextProps, thisState, nextState) {
    return !shallowEqualState(thisState, nextState) || !shallowEqualWithoutReactElements(thisProps, nextProps);
}
```

**Comment by mnpenner** [comment]
Is that really necessary? If you use the context (`this`) directly then we can just do

```js
class MyComponent extends React.Component {
    shouldComponentUpdate = shouldComponentUpdateChildren;
}
```

And the magic of JavaScript will pass the context along. Barring that, one can manually pass it via `.call` or the `::` bind operator.

**Comment by NoamELB** [comment]
I get what you mean, I will just add both 😅

**Comment by mnpenner** [comment]
Coolbeans :smile: Thanks!
